---

- include: "{{ ansible_os_family }}.yml"

- name: Enable selinux boolean haproxy_connect_any
  when: ansible_selinux and ansible_selinux.status == 'enabled'
  seboolean: name=haproxy_connect_any state=yes persistent=yes

- name: Determine haproxy version
  shell: '/usr/sbin/haproxy -v | grep version | sed -r "s/.+version ([0-9.]+) .+/\1/"'
  register: haproxy_version

- set_fact:
    haproxy_version: "{{ haproxy_version.stdout }}"

- debug:
    msg: "WARNING: load balancer health checks are not advisable for haproxy < 5"
  when: loadbalancer_healthcheck and haproxy_version < '5'

- name: haproxy config
  template:
    src=haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
    owner=root
    group=root
    mode=644
    backup=true

- name: haproxy started
  service: name=haproxy state=started

- name: reload haproxy
  service: name=haproxy state=reloaded
